export const dailyRoutineVocabulary = [
  { word: "wake up", meaning: "acordar", description: "To stop sleeping and become conscious" },
  { word: "get up", meaning: "levantar-se", description: "To leave your bed after waking up" },
  { word: "brush teeth", meaning: "escovar os dentes", description: "To clean your teeth with a toothbrush" },
  { word: "take a shower", meaning: "tomar banho", description: "To wash your body under running water" },
  { word: "get dressed", meaning: "se vestir", description: "To put on clothes" },
  { word: "have breakfast", meaning: "tomar café da manhã", description: "To eat the first meal of the day" },
  { word: "leave home", meaning: "sair de casa", description: "To go out of your house" },
  { word: "go to work", meaning: "ir ao trabalho", description: "To travel to your workplace" },
  { word: "go to school", meaning: "ir para a escola", description: "To attend school or classes" },
  { word: "study", meaning: "estudar", description: "To learn or review information" },

  { word: "work", meaning: "trabalhar", description: "To do your job or professional activity" },
  { word: "start work", meaning: "começar a trabalhar", description: "To begin your workday" },
  { word: "check emails", meaning: "ver e-mails", description: "To read and respond to emails" },
  { word: "attend a meeting", meaning: "participar de uma reunião", description: "To be present in a formal discussion" },
  { word: "take notes", meaning: "fazer anotações", description: "To write important information" },
  { word: "have lunch", meaning: "almoçar", description: "To eat the midday meal" },
  { word: "take a break", meaning: "fazer uma pausa", description: "To rest for a short time" },
  { word: "continue working", meaning: "continuar trabalhando", description: "To go on with your work" },
  { word: "finish work", meaning: "terminar o trabalho", description: "To complete your workday" },
  { word: "leave work", meaning: "sair do trabalho", description: "To go home after work" },

  { word: "go home", meaning: "ir para casa", description: "To return to your house" },
  { word: "cook dinner", meaning: "cozinhar o jantar", description: "To prepare the evening meal" },
  { word: "have dinner", meaning: "jantar", description: "To eat the evening meal" },
  { word: "wash the dishes", meaning: "lavar a louça", description: "To clean plates, cups, and utensils" },
  { word: "clean the house", meaning: "limpar a casa", description: "To organize and clean your home" },
  { word: "do homework", meaning: "fazer dever de casa", description: "To complete school tasks at home" },
  { word: "study again", meaning: "estudar novamente", description: "To review what you learned" },
  { word: "relax", meaning: "relaxar", description: "To rest and feel calm" },
  { word: "watch TV", meaning: "assistir TV", description: "To watch television programs" },
  { word: "use the phone", meaning: "usar o celular", description: "To spend time on your phone" },

  { word: "take a shower", meaning: "tomar banho", description: "To wash your body before sleeping" },
  { word: "put on pajamas", meaning: "vestir pijama", description: "To change into sleep clothes" },
  { word: "brush teeth", meaning: "escovar os dentes", description: "To clean your teeth before bed" },
  { word: "set the alarm", meaning: "ajustar o alarme", description: "To prepare an alarm to wake up" },
  { word: "go to bed", meaning: "ir para a cama", description: "To lie down to sleep" },
  { word: "fall asleep", meaning: "adormecer", description: "To begin sleeping" },
  { word: "sleep", meaning: "dormir", description: "To rest your body and mind" },
  { word: "wake up early", meaning: "acordar cedo", description: "To wake up before the usual time" },
  { word: "have a routine", meaning: "ter uma rotina", description: "To follow regular daily habits" }
] as const;